site_name: MCPReborn Wiki
site_url: https://mydomain.org/mysite
repo_url: https://github.com/archerv123456/MCPRWiki
extra_css:
  - css/index.css
theme:
  font:
    code: Source Code Pro
  name: material
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
nav:
  - Home: index.md
  - Guides: 
      - Home: guides/guideHome.md
      - Guides:
        - Getting Started: guides/Basics/FirstModification.md
        - Beginner:
          - Basic Knowledge: guides/Beginner/BasicKnowledge.md
          - Resources: guides/Beginner/Resources.md
          - Basic Items: guides/Beginner/Items.md
  - Reference:
    - Home: reference/home.md
    - Minecraft:
      - Advancements:
        - Advancement: reference/Minecraft/Advancements/Advancement.md
        - Advancement Holder: reference/Minecraft/Advancements/AdvancementHolder.md
        - Critereon:
          - AbstractCriterionTriggerInstance: reference/Minecraft/Advancements/Critereon/AbstractCriterionTriggerInstance.md
#   - MCP:
#   - Mojang:
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences